# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zigzagIOSChallange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for zigzagIOSChallange
pod 'XMLMapper', '~> 2.0'
  pod 'Alamofire', '~> 5.4'
  target 'zigzagIOSChallangeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'zigzagIOSChallangeUITests' do
    # Pods for testing
  end

end
